# Export all HashiCups services from dc1 to peer dc2.
# Apply on dc1 after peering is Active.
apiVersion: consul.hashicorp.com/v1alpha1
kind: ExportedServices
metadata:
  name: default
  namespace: consul
spec:
  services:
    - name: frontend
      consumers:
        - peer: dc2
    - name: public-api
      consumers:
        - peer: dc2
    - name: product-api
      consumers:
        - peer: dc2
    - name: payments
      consumers:
        - peer: dc2
    - name: postgres
      consumers:
        - peer: dc2
